- type: job
  id: Librarian
  name: job-name-librarian
  setPreference: false
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "Librarian"
  supervisors: job-supervisors-css
  access:
  - Service
  extendedAccess:
  - Maintenance

- type: startingGear
  id: LibrarianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d10Dice
  inhand:
    right hand: BriefcaseBrownFilled
  innerclothingskirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
